language: elixir
elixir:
  - 1.2.0
otp_release:
  - 18.0
notifications:
  recipients:
    - ricn@rny.io
before_install:
  - sudo add-apt-repository ppa:coolwanglu/pdf2htmlex --yes
  - sudo apt-get update -qq
  - sudo apt-get install pdf2htmlex libxslt-dev libxml2-dev
  - sudo apt-get install pdf2htmlex
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
after_success:
  - "mix compile && mix coveralls.travis"
